[package]
name = "spsc-bip-buffer"
version = "0.1.0"
authors = ["Andrea Lattuada <andrea@lattuada.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
deterministic = "*"
rand = "0.6"
